import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Satoshi = localFont({
  src: "./fonts/Satoshi-Variable.woff2",
  variable: "--font-satoshi",
  display: "fallback",
});
const Cabinet = localFont({
  src: "./fonts/CabinetGrotesk-Variable.woff2",
  variable: "--font-cabinet",
  display: "fallback",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Satoshi.variable} ${Cabinet.variable}`}>
        {children}
      </body>
    </html>
  );
}
